### ISSUE TITLE
Powder stacks convert to single Flux on pickup

### ISSUE THREAD

**Issue by Leden** [StrayWolfe/Cooking-with-TFC#3] opened 2016-11-19 07:50 UTC
When picking up powder entity items like kaolinite powder or saltpeter they all are converted into flux.
Probable cause of this is the flaw in `onItemPickup` handler which tries to convert TFC salt to CWTFC version, but as all powders share the Item class and differ only by damage metainformation, other powders do match the condition
`if(... || droppedItem == TFCItems.powder || ...) { //...`
and after that the damage info is just lost due to
`food = new ItemStack(droppedItem);` contains no damage parameter. I guess it defaults to zero, which means Flux powder.
I'm no Java coder so probably my guesses are wrong (:

**Comment by StrayWolfe** [comment] 2017-02-09 11:04
Thank you for the report and looking into what could be the cause. I'm not a Java coder either just a gamer that started playing with coding. You were correct with the cause of the bug. I added a fix and it will be in the next update. Thank you for posting.

**Closed as completed by StrayWolfe** 2017-02-09 11:04 UTC
